/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessProjectWorksRouteImport } from './routes/business.project-works'
import { Route as BusinessPartnershipRouteImport } from './routes/business.partnership'
import { Route as BusinessMaintenanceRouteImport } from './routes/business.maintenance'
import { Route as BusinessConstructionRouteImport } from './routes/business.construction'
import { Route as AboutStrengthsRouteImport } from './routes/about.strengths'
import { Route as AboutQualityRouteImport } from './routes/about.quality'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutHsseRouteImport } from './routes/about.hsse'
import { Route as AboutGovernanceRouteImport } from './routes/about.governance'
import { Route as AboutDeliveryRouteImport } from './routes/about.delivery'
import { Route as AboutCommitmentRouteImport } from './routes/about.commitment'
import { Route as AboutClientRouteImport } from './routes/about.client'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProjectWorksRoute = BusinessProjectWorksRouteImport.update({
  id: '/project-works',
  path: '/project-works',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPartnershipRoute = BusinessPartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMaintenanceRoute = BusinessMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessConstructionRoute = BusinessConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => BusinessRoute,
} as any)
const AboutStrengthsRoute = AboutStrengthsRouteImport.update({
  id: '/strengths',
  path: '/strengths',
  getParentRoute: () => AboutRoute,
} as any)
const AboutQualityRoute = AboutQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHsseRoute = AboutHsseRouteImport.update({
  id: '/hsse',
  path: '/hsse',
  getParentRoute: () => AboutRoute,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDeliveryRoute = AboutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AboutRoute,
} as any)
const AboutCommitmentRoute = AboutCommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => AboutRoute,
} as any)
const AboutClientRoute = AboutClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/network'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/network'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/network'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  ContactRoute: typeof ContactRoute
  NetworkRoute: typeof NetworkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/project-works': {
      id: '/business/project-works'
      path: '/project-works'
      fullPath: '/business/project-works'
      preLoaderRoute: typeof BusinessProjectWorksRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/partnership': {
      id: '/business/partnership'
      path: '/partnership'
      fullPath: '/business/partnership'
      preLoaderRoute: typeof BusinessPartnershipRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/maintenance': {
      id: '/business/maintenance'
      path: '/maintenance'
      fullPath: '/business/maintenance'
      preLoaderRoute: typeof BusinessMaintenanceRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/construction': {
      id: '/business/construction'
      path: '/construction'
      fullPath: '/business/construction'
      preLoaderRoute: typeof BusinessConstructionRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/about/strengths': {
      id: '/about/strengths'
      path: '/strengths'
      fullPath: '/about/strengths'
      preLoaderRoute: typeof AboutStrengthsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/quality': {
      id: '/about/quality'
      path: '/quality'
      fullPath: '/about/quality'
      preLoaderRoute: typeof AboutQualityRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/hsse': {
      id: '/about/hsse'
      path: '/hsse'
      fullPath: '/about/hsse'
      preLoaderRoute: typeof AboutHsseRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/delivery': {
      id: '/about/delivery'
      path: '/delivery'
      fullPath: '/about/delivery'
      preLoaderRoute: typeof AboutDeliveryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/commitment': {
      id: '/about/commitment'
      path: '/commitment'
      fullPath: '/about/commitment'
      preLoaderRoute: typeof AboutCommitmentRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/client': {
      id: '/about/client'
      path: '/client'
      fullPath: '/about/client'
      preLoaderRoute: typeof AboutClientRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutClientRoute: typeof AboutClientRoute
  AboutCommitmentRoute: typeof AboutCommitmentRoute
  AboutDeliveryRoute: typeof AboutDeliveryRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutHsseRoute: typeof AboutHsseRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutQualityRoute: typeof AboutQualityRoute
  AboutStrengthsRoute: typeof AboutStrengthsRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutClientRoute: AboutClientRoute,
  AboutCommitmentRoute: AboutCommitmentRoute,
  AboutDeliveryRoute: AboutDeliveryRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutHsseRoute: AboutHsseRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutQualityRoute: AboutQualityRoute,
  AboutStrengthsRoute: AboutStrengthsRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface BusinessRouteChildren {
  BusinessConstructionRoute: typeof BusinessConstructionRoute
  BusinessMaintenanceRoute: typeof BusinessMaintenanceRoute
  BusinessPartnershipRoute: typeof BusinessPartnershipRoute
  BusinessProjectWorksRoute: typeof BusinessProjectWorksRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessConstructionRoute: BusinessConstructionRoute,
  BusinessMaintenanceRoute: BusinessMaintenanceRoute,
  BusinessPartnershipRoute: BusinessPartnershipRoute,
  BusinessProjectWorksRoute: BusinessProjectWorksRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  ContactRoute: ContactRoute,
  NetworkRoute: NetworkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
