/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkIndexRouteImport } from './routes/network.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as NetworkPowerGenerationRouteImport } from './routes/network.power-generation'
import { Route as NetworkOilGasRouteImport } from './routes/network.oil-gas'
import { Route as NetworkLandTransportRouteImport } from './routes/network.land-transport'
import { Route as NetworkInfrastructureRouteImport } from './routes/network.infrastructure'
import { Route as NetworkGreenEnergyRouteImport } from './routes/network.green-energy'
import { Route as NetworkConstructionRouteImport } from './routes/network.construction'
import { Route as BusinessProjectWorksRouteImport } from './routes/business.project-works'
import { Route as BusinessPartnershipRouteImport } from './routes/business.partnership'
import { Route as BusinessMaintenanceRouteImport } from './routes/business.maintenance'
import { Route as BusinessConstructionRouteImport } from './routes/business.construction'
import { Route as AboutStrengthsRouteImport } from './routes/about.strengths'
import { Route as AboutQualityRouteImport } from './routes/about.quality'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutHsseRouteImport } from './routes/about.hsse'
import { Route as AboutGovernanceRouteImport } from './routes/about.governance'
import { Route as AboutDeliveryRouteImport } from './routes/about.delivery'
import { Route as AboutCommitmentRouteImport } from './routes/about.commitment'
import { Route as AboutClientRouteImport } from './routes/about/client'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const NetworkPowerGenerationRoute = NetworkPowerGenerationRouteImport.update({
  id: '/power-generation',
  path: '/power-generation',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkOilGasRoute = NetworkOilGasRouteImport.update({
  id: '/oil-gas',
  path: '/oil-gas',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkLandTransportRoute = NetworkLandTransportRouteImport.update({
  id: '/land-transport',
  path: '/land-transport',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkInfrastructureRoute = NetworkInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkGreenEnergyRoute = NetworkGreenEnergyRouteImport.update({
  id: '/green-energy',
  path: '/green-energy',
  getParentRoute: () => NetworkRoute,
} as any)
const NetworkConstructionRoute = NetworkConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => NetworkRoute,
} as any)
const BusinessProjectWorksRoute = BusinessProjectWorksRouteImport.update({
  id: '/project-works',
  path: '/project-works',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessPartnershipRoute = BusinessPartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessMaintenanceRoute = BusinessMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessConstructionRoute = BusinessConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => BusinessRoute,
} as any)
const AboutStrengthsRoute = AboutStrengthsRouteImport.update({
  id: '/strengths',
  path: '/strengths',
  getParentRoute: () => AboutRoute,
} as any)
const AboutQualityRoute = AboutQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHsseRoute = AboutHsseRouteImport.update({
  id: '/hsse',
  path: '/hsse',
  getParentRoute: () => AboutRoute,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDeliveryRoute = AboutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AboutRoute,
} as any)
const AboutCommitmentRoute = AboutCommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => AboutRoute,
} as any)
const AboutClientRoute = AboutClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/network': typeof NetworkRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
  '/network/construction': typeof NetworkConstructionRoute
  '/network/green-energy': typeof NetworkGreenEnergyRoute
  '/network/infrastructure': typeof NetworkInfrastructureRoute
  '/network/land-transport': typeof NetworkLandTransportRoute
  '/network/oil-gas': typeof NetworkOilGasRoute
  '/network/power-generation': typeof NetworkPowerGenerationRoute
  '/about/': typeof AboutIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/network/': typeof NetworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
  '/network/construction': typeof NetworkConstructionRoute
  '/network/green-energy': typeof NetworkGreenEnergyRoute
  '/network/infrastructure': typeof NetworkInfrastructureRoute
  '/network/land-transport': typeof NetworkLandTransportRoute
  '/network/oil-gas': typeof NetworkOilGasRoute
  '/network/power-generation': typeof NetworkPowerGenerationRoute
  '/about': typeof AboutIndexRoute
  '/business': typeof BusinessIndexRoute
  '/network': typeof NetworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/contact': typeof ContactRoute
  '/network': typeof NetworkRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/client': typeof AboutClientRoute
  '/about/commitment': typeof AboutCommitmentRoute
  '/about/delivery': typeof AboutDeliveryRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/hsse': typeof AboutHsseRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/quality': typeof AboutQualityRoute
  '/about/strengths': typeof AboutStrengthsRoute
  '/business/construction': typeof BusinessConstructionRoute
  '/business/maintenance': typeof BusinessMaintenanceRoute
  '/business/partnership': typeof BusinessPartnershipRoute
  '/business/project-works': typeof BusinessProjectWorksRoute
  '/network/construction': typeof NetworkConstructionRoute
  '/network/green-energy': typeof NetworkGreenEnergyRoute
  '/network/infrastructure': typeof NetworkInfrastructureRoute
  '/network/land-transport': typeof NetworkLandTransportRoute
  '/network/oil-gas': typeof NetworkOilGasRoute
  '/network/power-generation': typeof NetworkPowerGenerationRoute
  '/about/': typeof AboutIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/network/': typeof NetworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/network'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
    | '/network/construction'
    | '/network/green-energy'
    | '/network/infrastructure'
    | '/network/land-transport'
    | '/network/oil-gas'
    | '/network/power-generation'
    | '/about/'
    | '/business/'
    | '/network/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
    | '/network/construction'
    | '/network/green-energy'
    | '/network/infrastructure'
    | '/network/land-transport'
    | '/network/oil-gas'
    | '/network/power-generation'
    | '/about'
    | '/business'
    | '/network'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/network'
    | '/sitemap.xml'
    | '/about/client'
    | '/about/commitment'
    | '/about/delivery'
    | '/about/governance'
    | '/about/hsse'
    | '/about/leadership'
    | '/about/quality'
    | '/about/strengths'
    | '/business/construction'
    | '/business/maintenance'
    | '/business/partnership'
    | '/business/project-works'
    | '/network/construction'
    | '/network/green-energy'
    | '/network/infrastructure'
    | '/network/land-transport'
    | '/network/oil-gas'
    | '/network/power-generation'
    | '/about/'
    | '/business/'
    | '/network/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  ContactRoute: typeof ContactRoute
  NetworkRoute: typeof NetworkRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/': {
      id: '/network/'
      path: '/'
      fullPath: '/network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/network/power-generation': {
      id: '/network/power-generation'
      path: '/power-generation'
      fullPath: '/network/power-generation'
      preLoaderRoute: typeof NetworkPowerGenerationRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/oil-gas': {
      id: '/network/oil-gas'
      path: '/oil-gas'
      fullPath: '/network/oil-gas'
      preLoaderRoute: typeof NetworkOilGasRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/land-transport': {
      id: '/network/land-transport'
      path: '/land-transport'
      fullPath: '/network/land-transport'
      preLoaderRoute: typeof NetworkLandTransportRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/infrastructure': {
      id: '/network/infrastructure'
      path: '/infrastructure'
      fullPath: '/network/infrastructure'
      preLoaderRoute: typeof NetworkInfrastructureRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/green-energy': {
      id: '/network/green-energy'
      path: '/green-energy'
      fullPath: '/network/green-energy'
      preLoaderRoute: typeof NetworkGreenEnergyRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/network/construction': {
      id: '/network/construction'
      path: '/construction'
      fullPath: '/network/construction'
      preLoaderRoute: typeof NetworkConstructionRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/business/project-works': {
      id: '/business/project-works'
      path: '/project-works'
      fullPath: '/business/project-works'
      preLoaderRoute: typeof BusinessProjectWorksRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/partnership': {
      id: '/business/partnership'
      path: '/partnership'
      fullPath: '/business/partnership'
      preLoaderRoute: typeof BusinessPartnershipRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/maintenance': {
      id: '/business/maintenance'
      path: '/maintenance'
      fullPath: '/business/maintenance'
      preLoaderRoute: typeof BusinessMaintenanceRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/construction': {
      id: '/business/construction'
      path: '/construction'
      fullPath: '/business/construction'
      preLoaderRoute: typeof BusinessConstructionRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/about/strengths': {
      id: '/about/strengths'
      path: '/strengths'
      fullPath: '/about/strengths'
      preLoaderRoute: typeof AboutStrengthsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/quality': {
      id: '/about/quality'
      path: '/quality'
      fullPath: '/about/quality'
      preLoaderRoute: typeof AboutQualityRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/hsse': {
      id: '/about/hsse'
      path: '/hsse'
      fullPath: '/about/hsse'
      preLoaderRoute: typeof AboutHsseRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/delivery': {
      id: '/about/delivery'
      path: '/delivery'
      fullPath: '/about/delivery'
      preLoaderRoute: typeof AboutDeliveryRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/commitment': {
      id: '/about/commitment'
      path: '/commitment'
      fullPath: '/about/commitment'
      preLoaderRoute: typeof AboutCommitmentRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/client': {
      id: '/about/client'
      path: '/client'
      fullPath: '/about/client'
      preLoaderRoute: typeof AboutClientRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutClientRoute: typeof AboutClientRoute
  AboutCommitmentRoute: typeof AboutCommitmentRoute
  AboutDeliveryRoute: typeof AboutDeliveryRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutHsseRoute: typeof AboutHsseRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutQualityRoute: typeof AboutQualityRoute
  AboutStrengthsRoute: typeof AboutStrengthsRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutClientRoute: AboutClientRoute,
  AboutCommitmentRoute: AboutCommitmentRoute,
  AboutDeliveryRoute: AboutDeliveryRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutHsseRoute: AboutHsseRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutQualityRoute: AboutQualityRoute,
  AboutStrengthsRoute: AboutStrengthsRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface BusinessRouteChildren {
  BusinessConstructionRoute: typeof BusinessConstructionRoute
  BusinessMaintenanceRoute: typeof BusinessMaintenanceRoute
  BusinessPartnershipRoute: typeof BusinessPartnershipRoute
  BusinessProjectWorksRoute: typeof BusinessProjectWorksRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessConstructionRoute: BusinessConstructionRoute,
  BusinessMaintenanceRoute: BusinessMaintenanceRoute,
  BusinessPartnershipRoute: BusinessPartnershipRoute,
  BusinessProjectWorksRoute: BusinessProjectWorksRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface NetworkRouteChildren {
  NetworkConstructionRoute: typeof NetworkConstructionRoute
  NetworkGreenEnergyRoute: typeof NetworkGreenEnergyRoute
  NetworkInfrastructureRoute: typeof NetworkInfrastructureRoute
  NetworkLandTransportRoute: typeof NetworkLandTransportRoute
  NetworkOilGasRoute: typeof NetworkOilGasRoute
  NetworkPowerGenerationRoute: typeof NetworkPowerGenerationRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
}

const NetworkRouteChildren: NetworkRouteChildren = {
  NetworkConstructionRoute: NetworkConstructionRoute,
  NetworkGreenEnergyRoute: NetworkGreenEnergyRoute,
  NetworkInfrastructureRoute: NetworkInfrastructureRoute,
  NetworkLandTransportRoute: NetworkLandTransportRoute,
  NetworkOilGasRoute: NetworkOilGasRoute,
  NetworkPowerGenerationRoute: NetworkPowerGenerationRoute,
  NetworkIndexRoute: NetworkIndexRoute,
}

const NetworkRouteWithChildren =
  NetworkRoute._addFileChildren(NetworkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRouteWithChildren,
  ContactRoute: ContactRoute,
  NetworkRoute: NetworkRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
